name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-html

    - name: Run tests with Pytest
      run: |
        pytest --html=report.html

    - name: List files after tests
      run: dir

    - name: Upload HTML report
      uses: actions/upload-artifact@v3.1.2

      with:
        name: test-report
        path: report.html
